apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  labels:
    app: simulator 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: metalsoft/microservices-simulator
        command: [ "microservices-simulator"]
        args: ["-etcd","http://etcd-client:2379"]
        resources:
              limits:
                cpu: "4"
              requests:
                cpu: "4"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    microsrv: "true"
  name: microservices-simulator-service
spec:
  ports:
  - name: client
    port: 3365
    protocol: TCP
    targetPort: 3365
  selector:
    app: simulator
